/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module task4_6 (
    input clk,
    input rst,
    input in,
    output reg [2:0] out
  );
  
  
  
  localparam IDLE_state = 1'd0;
  localparam WIN_state = 1'd1;
  
  reg M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    out = 1'h0;
    
    case (M_state_q)
      IDLE_state: begin
        if (in == 1'h1) begin
          M_state_d = WIN_state;
        end
      end
      WIN_state: begin
        out = 3'h1;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
