/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module task1_3 (
    input clk,
    input rst,
    input w1,
    input w2,
    input w3,
    input w4,
    input w5,
    input w6,
    input enable,
    output reg [2:0] out
  );
  
  
  
  localparam IDLE_state = 4'd0;
  localparam W1_state = 4'd1;
  localparam W2_state = 4'd2;
  localparam W3_state = 4'd3;
  localparam W4_state = 4'd4;
  localparam W5_state = 4'd5;
  localparam W6_state = 4'd6;
  localparam WIN_state = 4'd7;
  localparam LOSE_state = 4'd8;
  
  reg [3:0] M_state_d, M_state_q = IDLE_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    out = 1'h0;
    
    case (M_state_q)
      IDLE_state: begin
        if (enable) begin
          M_state_d = W1_state;
        end
      end
      W1_state: begin
        if (!w1) begin
          M_state_d = W2_state;
        end
        if (!w2 || !w3 || !w4 || !w5 || !w6) begin
          M_state_d = LOSE_state;
        end
      end
      W2_state: begin
        if (!w2) begin
          M_state_d = W3_state;
        end
        if (!w3 || !w4 || !w5 || !w6) begin
          M_state_d = LOSE_state;
        end
      end
      W3_state: begin
        if (!w3) begin
          M_state_d = W4_state;
        end
        if (!w4 || !w5 || !w6) begin
          M_state_d = LOSE_state;
        end
      end
      W4_state: begin
        if (!w4) begin
          M_state_d = W5_state;
        end
        if (!w5 || !w6) begin
          M_state_d = LOSE_state;
        end
      end
      W5_state: begin
        if (!w5) begin
          M_state_d = W6_state;
        end
        if (!w6) begin
          M_state_d = LOSE_state;
        end
      end
      W6_state: begin
        if (!w6) begin
          M_state_d = WIN_state;
        end
      end
      WIN_state: begin
        out = 3'h1;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h0;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
