/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module time_digit_8 (
    input [8:0] in,
    output reg [5:0] out2,
    output reg [5:0] out1,
    output reg [5:0] out0
  );
  
  
  
  always @* begin
    if (in <= 4'h9) begin
      out2 = 6'h0a;
      out1 = 6'h00;
      out0 = in[0+5-:6];
    end else begin
      if (in <= 5'h13) begin
        out2 = 6'h0a;
        out1 = 6'h01;
        out0 = in - 4'ha;
      end else begin
        if (in <= 5'h1d) begin
          out2 = 6'h0a;
          out1 = 6'h02;
          out0 = in - 5'h14;
        end else begin
          if (in <= 6'h27) begin
            out2 = 6'h0a;
            out1 = 6'h03;
            out0 = in - 5'h1e;
          end else begin
            if (in <= 6'h31) begin
              out2 = 6'h0a;
              out1 = 6'h04;
              out0 = in - 6'h28;
            end else begin
              if (in <= 6'h3b) begin
                out2 = 6'h0a;
                out1 = 6'h05;
                out0 = in - 6'h32;
              end else begin
                if (in <= 7'h45) begin
                  out2 = 6'h0b;
                  out1 = 6'h00;
                  out0 = in - 6'h3c;
                end else begin
                  if (in <= 7'h4f) begin
                    out2 = 6'h0b;
                    out1 = 6'h01;
                    out0 = in - 7'h46;
                  end else begin
                    if (in <= 7'h59) begin
                      out2 = 6'h0b;
                      out1 = 6'h02;
                      out0 = in - 7'h50;
                    end else begin
                      if (in <= 7'h63) begin
                        out2 = 6'h0b;
                        out1 = 6'h03;
                        out0 = in - 7'h5a;
                      end else begin
                        if (in <= 7'h6d) begin
                          out2 = 6'h0b;
                          out1 = 6'h04;
                          out0 = in - 7'h64;
                        end else begin
                          if (in <= 7'h77) begin
                            out2 = 6'h0b;
                            out1 = 6'h05;
                            out0 = in - 7'h6e;
                          end else begin
                            if (in <= 8'h81) begin
                              out2 = 6'h0c;
                              out1 = 6'h00;
                              out0 = in - 7'h78;
                            end else begin
                              if (in <= 8'h8b) begin
                                out2 = 6'h0c;
                                out1 = 6'h01;
                                out0 = in - 8'h82;
                              end else begin
                                if (in <= 8'h95) begin
                                  out2 = 6'h0c;
                                  out1 = 6'h02;
                                  out0 = in - 8'h8c;
                                end else begin
                                  if (in <= 8'h9f) begin
                                    out2 = 6'h0c;
                                    out1 = 6'h03;
                                    out0 = in - 8'h96;
                                  end else begin
                                    if (in <= 8'ha9) begin
                                      out2 = 6'h0c;
                                      out1 = 6'h04;
                                      out0 = in - 8'ha0;
                                    end else begin
                                      if (in <= 8'hb3) begin
                                        out2 = 6'h0c;
                                        out1 = 6'h05;
                                        out0 = in - 8'haa;
                                      end else begin
                                        if (in <= 8'hbd) begin
                                          out2 = 6'h0d;
                                          out1 = 6'h00;
                                          out0 = in - 8'hb4;
                                        end else begin
                                          if (in <= 8'hc7) begin
                                            out2 = 6'h0d;
                                            out1 = 6'h01;
                                            out0 = in - 8'hbe;
                                          end else begin
                                            if (in <= 8'hd1) begin
                                              out2 = 6'h0d;
                                              out1 = 6'h02;
                                              out0 = in - 8'hc8;
                                            end else begin
                                              if (in <= 8'hdb) begin
                                                out2 = 6'h0d;
                                                out1 = 6'h03;
                                                out0 = in - 8'hd2;
                                              end else begin
                                                if (in <= 8'he5) begin
                                                  out2 = 6'h0d;
                                                  out1 = 6'h04;
                                                  out0 = in - 8'hdc;
                                                end else begin
                                                  if (in <= 8'hef) begin
                                                    out2 = 6'h0d;
                                                    out1 = 6'h05;
                                                    out0 = in - 8'he6;
                                                  end else begin
                                                    if (in <= 8'hf9) begin
                                                      out2 = 6'h0e;
                                                      out1 = 6'h00;
                                                      out0 = in - 8'hf0;
                                                    end else begin
                                                      if (in <= 9'h103) begin
                                                        out2 = 6'h0e;
                                                        out1 = 6'h01;
                                                        out0 = in - 8'hfa;
                                                      end else begin
                                                        if (in <= 9'h10d) begin
                                                          out2 = 6'h0e;
                                                          out1 = 6'h02;
                                                          out0 = in - 9'h104;
                                                        end else begin
                                                          if (in <= 9'h117) begin
                                                            out2 = 6'h0e;
                                                            out1 = 6'h03;
                                                            out0 = in - 9'h10e;
                                                          end else begin
                                                            if (in <= 9'h121) begin
                                                              out2 = 6'h0e;
                                                              out1 = 6'h04;
                                                              out0 = in - 9'h118;
                                                            end else begin
                                                              if (in <= 9'h12b) begin
                                                                out2 = 6'h0e;
                                                                out1 = 6'h05;
                                                                out0 = in - 9'h122;
                                                              end else begin
                                                                if (in <= 9'h135) begin
                                                                  out2 = 6'h0f;
                                                                  out1 = 6'h00;
                                                                  out0 = in - 9'h12c;
                                                                end else begin
                                                                  out2 = 1'h0;
                                                                  out1 = 1'h0;
                                                                  out0 = 1'h0;
                                                                end
                                                              end
                                                            end
                                                          end
                                                        end
                                                      end
                                                    end
                                                  end
                                                end
                                              end
                                            end
                                          end
                                        end
                                      end
                                    end
                                  end
                                end
                              end
                            end
                          end
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end
endmodule
