/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cd_timer_2 (
    input clk,
    input rst,
    input [8:0] in,
    input [1:0] enable,
    output reg [8:0] out
  );
  
  
  
  reg [25:0] M_counter_d, M_counter_q = 1'h0;
  reg [1:0] M_eo_d, M_eo_q = 1'h0;
  reg [7:0] M_countdown_d, M_countdown_q = 1'h0;
  localparam COUNT_state = 1'd0;
  localparam WAIT_state = 1'd1;
  
  reg M_state_d, M_state_q = COUNT_state;
  
  always @* begin
    M_state_d = M_state_q;
    M_countdown_d = M_countdown_q;
    M_counter_d = M_counter_q;
    M_eo_d = M_eo_q;
    
    
    case (enable)
      1'h1: begin
        M_eo_d = M_eo_q + 1'h1;
      end
      2'h2: begin
        M_eo_d = M_eo_q + 1'h1;
      end
    endcase
    out = in - M_countdown_q;
    
    case (M_state_q)
      COUNT_state: begin
        M_counter_d = 1'h0;
        if (M_eo_q == 1'h1) begin
          M_state_d = WAIT_state;
        end
      end
      WAIT_state: begin
        M_counter_d = M_counter_q + 1'h1;
        if (M_eo_q == 2'h2) begin
          M_state_d = COUNT_state;
        end
        if (M_counter_q == 26'h2faf07f) begin
          M_countdown_d = M_countdown_q + 1'h1;
          M_state_d = COUNT_state;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counter_q <= 1'h0;
      M_eo_q <= 1'h0;
      M_countdown_q <= 1'h0;
      M_state_q <= 1'h0;
    end else begin
      M_counter_q <= M_counter_d;
      M_eo_q <= M_eo_d;
      M_countdown_q <= M_countdown_d;
      M_state_q <= M_state_d;
    end
  end
  
endmodule
